import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import Session from "@/providers/sessionProvider";
import "./globals.css";
import Navbar from "./component/layout/navbar";
import Footer from "./component/layout/footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Session>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </Session>
      </body>
    </html>
  );
}
